# Generated by Django 2.1.7 on 2019-03-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.IntegerField(choices=[(1, 'ill'), (2, 'badboy'), (3, 'timeout')], default=1)),
                ('day', models.DateField()),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('job_place', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PupilModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], default='f', max_length=1)),
                ('address', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('group', models.IntegerField(default=1, verbose_name=((1, ''), (2, ''), (3, '')))),
                ('vision_defect', models.BooleanField(default=False)),
                ('discount', models.IntegerField(choices=[(1, 'No discount'), (2, '')], default=1)),
                ('parent', models.ManyToManyField(to='monitoring.ParentModel')),
                ('pupil_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.ClassModel')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='classmodel',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.TeacherModel'),
        ),
        migrations.AddField(
            model_name='absencemodel',
            name='pupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.PupilModel'),
        ),
    ]
