# Generated by Django 2.1.7 on 2019-03-15 19:12

from django.db import migrations


def add_teachers(apps, schema_editor):
    TeacherModel = apps.get_model('monitoring', 'TeacherModel')

    data = [
        ['Ерстенюк', 'Михайло', 'Іванович'],
        ['Михайлюк', 'Іванна', 'Мирославівна'],
        ['Галаник', 'Оксана', 'Іванівна'],
        ['Гладун', 'Лідія', 'Анатоліївна'],
        ['Шваєвська', 'Оксана', 'Михайлівна'],
        ['Карплюк', 'Надія', 'Дмитрівна'],
        ['Школик', 'Ганна', 'Богданівна'],
        ['Уманець', 'Надія', 'Миколаївна'],
        ['Ящишинa', 'Наталія', 'Ярославівна'],
        ['Кулик', 'Андрій', 'Михайлович'],
        ['Самотіс', 'Лідія', 'Романівна'],
        ['Бевзюк', 'Антон', 'Андрійович'],
        ['Вишинський', 'Володимир', 'Анатолійович'],
        ['Крашевська', 'Ганна', 'Йосипівна'],
        ['Полуліх', 'Євгенія', 'Павлівна'],
        ['Осецька', 'Наталія', 'Ігорівна'],
        ['Вельгош', 'Олеся', 'Миронівна'],
        ['Клим', 'Мирослава', 'Володимирівна'],
        ['Лукашів', 'Михайло', 'Іванович'],
        ['Смішко', 'Любов', 'Олександрівна'],
    ]

    for teacher_data in range(len(data)):
        teacher = TeacherModel(
            last_name=data[teacher_data][0],
            first_name=data[teacher_data][1],
            middle_name=data[teacher_data][2],
        )
        teacher.save()


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_teachers),
    ]
