# Generated by Django 2.1.7 on 2019-03-15 19:27

from django.db import migrations


def add_classes(apps, schema_editor):
    ClassModel = apps.get_model('monitoring', 'ClassModel')
    TeacherModel = apps.get_model('monitoring', 'TeacherModel')

    data = [
        ['1-А', '1'],
        ['1-Б', '2'],
        ['2-А', '3'],
        ['2-Б', '4'],
        ['3-А', '5'],
        ['3-Б', '6'],
        ['4-А', '7'],
        ['4-Б', '8'],
        ['5-А', '9'],
        ['5-Б', '10'],
        ['6-А', '11'],
        ['6-Б', '12'],
        ['7-А', '13'],
        ['7-Б', '14'],
        ['8-А', '15'],
        ['8-Б', '16'],
        ['9-А', '17'],
        ['9-Б', '18'],
        ['10-А', '19'],
        ['11-А', '20'],
    ]

    for class_data in range(len(data)):
        clss = ClassModel(
            name=data[class_data][0],
            teacher=TeacherModel.objects.get(id=data[class_data][1]),
        )
        clss.save()


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_teachers_migration'),
    ]

    operations = [
        migrations.RunPython(add_classes),
    ]
