# Generated by Django 2.1.7 on 2019-04-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_pupil_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencemodel',
            name='cause',
            field=models.IntegerField(choices=[(1, 'Хвороба'), (2, 'Прогул'), (3, 'Запізнення')], default=1),
        ),
        migrations.AlterField(
            model_name='pupilmodel',
            name='discount',
            field=models.IntegerField(choices=[(1, 'Пільг немає'), (2, 'З особливими освітніми потребами, які навчаються у спеціальних і інклюзивних класах'), (3, 'Діти-сироти та діти, позбавлені батьківського піклування'), (4, 'Діти із малозабезпечених сімей, що отримують допомогу'), (5, 'Діти працівників органів внутрішніх справ, які загинули під час виконання службових обов`язків'), (6, 'Діти із сімей учасників бойових дій та діти із сімей загиблих учасників бойових дій'), (7, 'Діти, які потрапили у складні життєві умови'), (8, 'Діти, які є інвалідами внаслідок Чорнобильської катастрофи')], default=1),
        ),
        migrations.AlterField(
            model_name='pupilmodel',
            name='gender',
            field=models.CharField(choices=[('f', 'Жіноча'), ('m', 'Чоловіча')], default='f', max_length=1),
        ),
        migrations.AlterField(
            model_name='pupilmodel',
            name='group',
            field=models.IntegerField(choices=[(1, 'Основна група'), (2, 'Підготовча група'), (3, 'Спеціальна група')], default=1),
        ),
    ]
