# Generated by Django 2.2 on 2019-05-25 12:08
import os
from django.contrib.auth.hashers import make_password
from django.db import migrations


def add_admin(apps, schema_editor):
    UserModel = apps.get_model('auth', 'User')

    user = UserModel(
        username='admin',
        password=make_password(os.getenv('ADMIN_PASSWORD'))
    )
    user.save()


def del_admin(apps, schema_editor):
    UserModel = apps.get_model('auth', 'User')

    user = UserModel.objects.get(username='admin')
    user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_auto_20190507_1954'),
    ]

    operations = [
        migrations.RunPython(code=add_admin, reverse_code=del_admin)
    ]
